### ISSUE TITLE
esto podría estar incluido en el footer para que todos los JS vayan al mismo lugar

### ISSUE THREAD

**Issue by julianbutti** [santipdmonte/BajoRosario-Shopping#9]
https://github.com/santipdmonte/BajoRosario-Shopping/blob/b59db4060e91483b2f45ff5ee22cc6bc3d2c5a70/src/views/promociones_slider.php#L38

**Comment by santipdmonte** [comment]
Se utiliza únicamente en ese componente, por eso lo agregamos dentro de ese archivo

**Comment by santipdmonte** [comment]
Se utiliza únicamente en ese componente, por eso lo agregamos dentro de ese archivo
